# Generated by Django 2.2.5 on 2019-09-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descr', models.CharField(max_length=100, verbose_name='Description')),
                ('status', models.CharField(default='new', max_length=50, verbose_name='Status')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Completion date')),
            ],
        ),
    ]
