# Generated by Django 2.2.5 on 2019-09-05 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('New', 'new'), ('In progress', 'in progress'), ('Done', 'done')], default='new', max_length=50, verbose_name='Status'),
        ),
    ]
