# Generated by Django 2.2.5 on 2019-09-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20190905_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='full_description',
            field=models.TextField(blank=True, max_length='3000', null=True, verbose_name='Full description'),
        ),
    ]
